apiVersion: apps/v1
kind: Deployment
metadata:
  name: stakater-frontend
  namespace: stakater
  labels:
    app: stakater-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stakater-frontend
  template:
    metadata:
      labels:
        app: stakater-frontend
    spec:
      containers:
      - name: stakater-frontend
        image: stakater-frontend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stakater-frontend
  name: stakater-frontend
  namespace: stakater
spec:
  ports:
  - name: 
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: stakater-frontend
  type: ClusterIP
